## YAML Template.
name: RunicParadise
author: runelynx
description: "Bukkit plugin for Runic Paradise server."
main: io.github.runelynx.runicparadise.RunicParadise
version: 0.1
depend: [NoteBlockAPI]
commands:
   sendentity:
      description: "Sends a living entity to a player"
      usage: /<command> [player]
      permission: rp.staff.sendentity
      permission-message: "You don't have permission: rp.staff.sendentity"
   el:
      description: "Staff commands for explorer's league"
      usage: /<command>
      permission: rp.staff.explorersleague
      permission-message: "You don't have permission: rp.staff.explorersleague"
   carnivalaxe:
      description: "Create a carnival axe"
      usage: /<command>
      permission: rp.staff.carnivalaxe
      permission-message: "You don't have permission: rp.freezemob."
   casino:
      description: "Manage casino"
      usage: /<command>
      permission: rp.casino.admin
      permission-message: "You don't have permission: rp.casino.admin"
   freezemob:
      description: "Freeze a mob!"
      usage: /<command>
      permission: rp.freezemob
      permission-message: "You don't have permission: rp.freezemob."
   unfreezemob:
      description: "UnFreeze a mob!"
      usage: /<command>
      permission: rp.freezemob
      permission-message: "You don't have permission: rp.freezemob."
   consoleseeker:
      description: "Promote seeker from skyblock"
      usage: /<command>
      permission: rp.admin
      permission-message: "You don't have permission: <permission>"
   mw:
      description: "Go to the mining world portal"
      usage: /<command>
   miningworld:
      description: "Go to the mining world portal"
      usage: /<command> 
   wild:
      description: "Head out into the wilderness!"
      usage: /<command> 
   runiceye:
      description: "Meh - for Rune!"
      usage: /<command> [player]
      permission: rp.admin
      permission-message: "You don't have permission: <permission>"
   headofplayer:
      description: "Used to create player heads. Once every 6 hours ONLY!"
      usage: /<command> [playername]
      permission: rp.face
      permission-message: "You don't have permission: <permission>. [Rank Hunter and above]"
   holotest:
      description: "Rune testing things"
      usage: /<command> [1/2]
      permission: rp.admin
      permission-message: "You don't have permission: <permission>."
   miningreset:
      description: "Resets the mining world"
      usage: /<command> [playername]
      permission: rp.admin
      permission-message: "You don't have permission: <permission>."
   face:
      description: "Used to create player heads. Once every 6 hours ONLY!"
      usage: /<command> [playername]
      permission: rp.face
      permission-message: "You don't have permission: <permission>. [Rank Hunter and above]"
   miningworldreminder:
      description: "Reminder for scheduled announcement"
      usage: /<command>
      permission: rp.mwr
      permission-message: "This is for admins only."
   iteminfo:
      description: "Gets detailed item info."
      usage: /<command>
      permission: rp.iteminfo
      permission-message: "Staff only."
   gift:
      description: "Used to send and receive gifts."
      usage: /<command>
      permission: rp.gift
      permission-message: "Sorry this command is not available right now."
   crocomaze:
      description: "Used by Rune (only) in the CrocoMaze"
      usage: /<command>
      permission: rp.crocomaze
      permission-message: "Sorry this command is not for players to use."
   cactifever:
      description: "Are you infected by cacti fever??"
      usage: /<command>
      permission: rp.cactifever
      permission-message: "Thankfully we stopped the spread of cacti fever!! Sorry :x"
   dailykarma:
      description: "Runic Paradise /say override command"
      usage: /<command> [player]
      permission: rp.admin
      permission-message: "You don't have permission: <permission>"
   adventureparkourprize:
      description: "Claim prize for the Adventure Parkour"
      usage: /<command> [player]
      permission: rp.admin
      permission-message: "You don't have permission: <permission>"
   junglemaze:
      description: "Command blocks in the jungle maze. Not for use by players."
      permission: rp.admin
      permission-message: "You don't have permission: <permission>"
   oldrankperks:
      description: "Restore perks from your old rank"
      usage: /<command> [oldrankname]
   say:
      description: "Runic Paradise /say override command"
      usage: /<command> [player]
      permission: rp.staff
      permission-message: "You don't have permission: <permission>"
   voice:
      description: "Voice chat info"
      usage: /<command> 
   discord:
      description: "Voice chat info"
      usage: /<command> 
   powers:
      description: "Runic Powers command"
      usage: /<command> 
      permission: rp.staff.powers
      permission-message: "You don't have permission: <permission>"
   faith:
      description: "Runic Faith command"
      usage: /<command> 
      permission: rp.faith
      permission-message: "You don't have permission: <permission>"
   punish:
      description: "Staff tool for keeping the peace"
      usage: /<command> [player]
      permission: rp.staff
      permission-message: "You don't have permission: <permission>"
   rp:
      description: "Rune's first custom command. Sends you to spawn."
      usage: /<command> [player]
   rpvote:
      description: "A workaround for voting rewards - console only!!"
      usage: /<command>
      permission: rp.NoPlayersAllowed
      permission-message: "You don't have permission: <permission>"
   seeker:
      description: "For promoting ghosts."
      usage: /<command>
      permission: rp.settlerpromotions
      permission-message: "You don't have permission: <permission>"
   disguise:
      description: "For promoting ghosts."
      usage: /<command>
      permission: rp.settlerpromotions
      permission-message: "You don't have permission: <permission>"
   settler:
      description: "For promoting ghosts."
      usage: /<command>
      permission: rp.settlerpromotions
      permission-message: "You don't have permission: <permission>"
   rpjobs:
      description: "Job mastery command. Console only!"
      usage: /<command>
      permission: rp.NoPlayersAllowed
      permission-message: "You don't have permission: <permission>"
   rpeffects:
      description: "Create particle effects!"
      usage: /<command>
      permission: rp.NoPlayersAllowed
      permission-message: "You don't have permission: <permission>"
   grave:
      description: "RunicReaper's graves command"
      usage: /<command>
      permission: rp.graves
      permission-message: "You don't have permission: <permission>"
   graves:
      description: "RunicReaper's graves command"
      usage: /<command>
      permission: rp.graves
      permission-message: "You don't have permission: <permission>"
   rptransfer:
      description: "Used by command blocks to save/load inventory for special events"
      usage: /<command>
      permission: rp.staff
      permission-message: "You don't have permission: <permission>"
   rpmail:
      description: "A test command for the email system"
      usage: /<command>
      permission: rp.test
   rptokens:
      description: "Used by staff for Runic Carnival"
      usage: /<command>
      permission: rp.staff
   radio:
      description: "Join our DJ booth!"
      usage: /<command>
   ready:
      description: "Let us know you're ready to start building on the server. This notifies staff you need a promotion to Settler."
      usage: /<command>
      permission: rp.ghost
      permission-message: "Only Ghosts can use this command."
   music:
      description: "Join our DJ booth!"
      usage: /<command>
   rptest:
      description: "Sends test messages based on the config file"
      usage: /<command>
      permission: runicparadise.rptest
      permission-message: "You don't have permission: <permission>"
   staff:
      description: "Menu of staff commands"
      permission: rp.staff
      permission-message: "Only staff (mods/admins) can use this command."
   staffchat:
      description: "Channel where staff can chat together"
      permission: rp.staff
      permission-message: "Only staff (mods/admins) can use this command."
   promote:
      description: "Runic Paradise Promotion Command"
   rankup:
      description: "Runic Paradise Promotion Command"
   ranks:
      description: "Display requirements for each rank"
   sc:
      description: "Channel where staff can chat together"
      permission: rp.staff
      permission-message: "Only staff (mods/admins) can use this command."
   tc:
      description: "Channel where testers can chat together"
      permission: rp.testers
      permission-message: "Only testers can use this command."
   rpreload:
      description: "Reloads the Runic Paradise plugin config file."
      usage: /<command>
      permission: runicparadise.rpreload
      permission-message: "You don't have permission: <permission>"
   games:
      description: "Runic Paradise games menu."
      usage: /<command> [option]
   rpgames:
      description: "Runic Paradise games menu."
      usage: /<command> [option]
   events:
      description: "Runic Paradise events tool."
      usage: /<command> [option]
   hmsay:
      description: "Herobrines Mansion message command."
      usage: /<command> [option]    
