## Runic Paradise Plugin Config File
---
## Test Messages
testAnnouncement: "Testing!"
testPersonalMessage: "Testing personal message!"

## MySQL Connection details
dbHost: Testing
dbPort: 3301
dbDabatase: Db
dbUser: User
dbPassword: pw

## Gaming menu
game1Name: "Herobrine's Mansion (Adventure Map)"
game1CmdType: teleport
game1Detail: 5666 73 2 1 89.65
game2Name: "Floating Isle MobArena"
game2CmdType: command
game2Detail: ma join isle
game3Name: "Tigorien Spleef Arena"
game3CmdType: command
game3Detail: pa tigospleef
game4Name: "Coming soon"
game4CmdType: unused
game4Detail: 0 0 0 0 0
game5Name: "Coming soon"
game5CmdType: unused
game5Detail: 0 0 0 0 0
