## YAML Template.
name: RunicParadise
author: runelynx
description: "Bukkit plugin for Runic Paradise server."
main: io.github.runelynx.runicparadise.RunicParadise
version: 1.1
#depend: [NoteBlockAPI, WorldGuard, RunicUniverse, CS-CoreLib, Slimefun]
depend: [NoteBlockAPI, RunicUniverse]
api-version: 1.13
commands:
   rpcrates:
      description: "Grant Runic currencies to a player"
      usage: /<command>
      permission: rp.rpcrates
      permission-message: "Missing permission: rp.rpcrates"
   rprewards:
      description: "Grant Runic currencies to a player"
      usage: /<command>
      permission: rp.rprewards
      permission-message: "Missing permission: rp.rprewards"
   claim:
      description: "Create a claim"
      usage: /<command>
      permission: rp.claim
      permission-message: "Missing permission: rp.claim"
   machinemaze:
      description: "Machine Maze Magic"
      usage: /<command>
      permission: rp.machinemaze
      permission-message: "Not for player usage!"
   faithweapons:
      description: "Gives user all faith weapons"
      usage: /<command>
      permission: rp.staff.faithweapons
      permission-message: "Not for player usage!"
   faithweapon:
      description: "Specify a player to give a faith weapon to (sword1/sword2/sword3/axe1). "
      usage: /<command> <weapon code> <player name>
      permission: rp.staff.faithweapon
      permission-message: "Not for player usage!"
   rankitem:
      description: "Rank item magic :)"
      usage: /<command>
      permission: rp.rankitem
      permission-message: "Not for player usage!"
   raffle:
      description: "Runic Raffle"
      usage: /<command>
      permission: rp.raffle
      permission-message: "The raffle isn't open yet!"
   fixranks:
      description: "Fix rank problems."
      usage: /<command>
      permission: rp.fixranks
      permission-message: "You don't have permission: rp.fixranks"
   rpfix:
      description: "Donation perk. Repairs item in both hands."
      usage: /<command>
      permission: rp.repair.disabled
      permission-message: "/rpfix is disabled!"
   runicspawntravel:
      description: "Just for admins"
      usage: /<command>
      permission: rp.runicspawntravel
      permission-message: "You don't have permission: rp.runicspawntravel"
   search:
      description: "Search for Explorer's League locations. See /games for info"
      usage: /<command>
      permission: rp.explorersleague
      permission-message: "You don't have permission: rp.explorersleague"
   explore:
      description: "Search for Explorer's League locations. See /games for info"
      usage: /<command>
      permission: rp.explorersleague
      permission-message: "You don't have permission: rp.explorersleague"
   el:
      description: "Staff commands for explorer's league"
      usage: /<command>
      permission: rp.staff.explorersleague
      permission-message: "You don't have permission: rp.staff.explorersleague"
   casino:
      description: "Manage casino"
      usage: /<command>
      permission: rp.casino.admin
      permission-message: "You don't have permission: rp.casino.admin"
   freezemob:
      description: "Freeze a mob!"
      usage: /<command>
      permission: rp.freezemob
      permission-message: "You don't have permission: rp.freezemob."
   unfreezemob:
      description: "UnFreeze a mob!"
      usage: /<command>
      permission: rp.freezemob
      permission-message: "You don't have permission: rp.freezemob."
   consoleseeker:
      description: "Promote seeker from skyblock"
      usage: /<command>
      permission: rp.admin
      permission-message: "You don't have permission: <permission>"
   mw:
      description: "Go to the mining world portal"
      usage: /<command>
   miningworld:
      description: "Go to the mining world portal"
      usage: /<command> 
   wild:
      description: "Head out into the wilderness!"
      usage: /<command>
      permission: rp.seeker
      permission-message: "You must finish the tutorial before you start playing! Use /spawn to go back. A sign toward the end will tell you how to promote to seeker!" 
   runiceye:
      description: "Meh - for Rune!"
      usage: /<command> [player]
      permission: rp.admin
      permission-message: "You don't have permission: <permission>"
   headofplayer:
      description: "Used to create player heads. Once every 6 hours ONLY!"
      usage: /<command> [playername]
      permission: rp.face
      permission-message: "You don't have permission: <permission>. [Rank Hunter and above]"
   holotest:
      description: "Rune testing things"
      usage: /<command> [1/2]
      permission: rp.admin
      permission-message: "You don't have permission: <permission>."
   miningreset:
      description: "Resets the mining world"
      usage: /<command> [playername]
      permission: rp.admin.miningreset
      permission-message: "You don't have permission: <permission>."
   face:
      description: "Used to create player heads. Once every 6 hours ONLY!"
      usage: /<command> [playername]
      permission: rp.face
      permission-message: "You don't have permission: <permission>. [Rank Hunter and above]"
   miningworldreminder:
      description: "Reminder for scheduled announcement"
      usage: /<command>
      permission: rp.mwr
      permission-message: "This is for admins only."
   iteminfo:
      description: "Gets detailed item info."
      usage: /<command>
      permission: rp.iteminfo
      permission-message: "Staff only."
   crocomaze:
      description: "Used by Rune (only) in the CrocoMaze"
      usage: /<command>
      permission: rp.crocomaze
      permission-message: "Sorry this command is not for players to use."
   cactifever:
      description: "Are you infected by cacti fever??"
      usage: /<command>
      permission: rp.cactifever
      permission-message: "Thankfully we stopped the spread of cacti fever!! Sorry :x"
   dailykarma:
      description: "Runic Paradise /say override command"
      usage: /<command> [player]
      permission: rp.admin
      permission-message: "You don't have permission: <permission>"
   adventureparkourprize:
      description: "Claim prize for the Adventure Parkour"
      usage: /<command> [player]
      permission: rp.admin
      permission-message: "You don't have permission: <permission>"
   junglemaze:
      description: "Command blocks in the jungle maze. Not for use by players."
      permission: rp.admin
      permission-message: "You don't have permission: <permission>"
   say:
      description: "Runic Paradise /say override command"
      usage: /<command> [player]
      permission: rp.staff
      permission-message: "You don't have permission: <permission>"
   voice:
      description: "Voice chat info"
      usage: /<command> 
   discord:
      description: "Voice chat info"
      usage: /<command> 
   powers:
      description: "Runic Powers command"
      usage: /<command> 
      permission: rp.staff.powers
      permission-message: "You don't have permission: <permission>"
   faith:
      description: "Runic Faith command"
      usage: /<command> 
      permission: rp.faith
      permission-message: "You don't have permission: <permission>"
   punish:
      description: "Staff tool for keeping the peace"
      usage: /<command> [player]
      permission: rp.staff
      permission-message: "You don't have permission: <permission>"
   rp:
      description: "Rune's first custom command. Sends you to spawn."
      usage: /<command> [player]
   rpvote:
      description: "A workaround for voting rewards - console only!!"
      usage: /<command>
      permission: rp.NoPlayersAllowed
      permission-message: "You don't have permission: <permission>"
   seeker:
      description: "For promoting ghosts."
      usage: /<command>
      permission: rp.settlerpromotions
      permission-message: "You don't have permission: <permission>"
   disguise:
      description: "For promoting ghosts."
      usage: /<command>
      permission: rp.settlerpromotions
      permission-message: "You don't have permission: <permission>"
   settler:
      description: "For promoting ghosts."
      usage: /<command>
      permission: rp.settlerpromotions
      permission-message: "You don't have permission: <permission>"
   rpjobs:
      description: "Job mastery command. Console only!"
      usage: /<command>
      permission: rp.NoPlayersAllowed
      permission-message: "You don't have permission: <permission>"
   rpeffects:
      description: "Create particle effects!"
      usage: /<command>
      permission: rp.NoPlayersAllowed
      permission-message: "You don't have permission: <permission>"
   rptokens:
      description: "Used by staff for Runic Carnival"
      usage: /<command>
      permission: rp.staff
   radio:
      description: "Join our DJ booth!"
      usage: /<command>
   ready:
      description: "Let us know you're ready to start building on the server. This notifies staff you need a promotion to Settler."
      usage: /<command>
      permission: rp.ghost
      permission-message: "Only Ghosts can use this command."
   music:
      description: "Join our DJ booth!"
      usage: /<command>
   rptest:
      description: "Sends test messages based on the config file"
      usage: /<command>
      permission: runicparadise.rptest
      permission-message: "You don't have permission: <permission>"
   staff:
      description: "Menu of staff commands"
      permission: rp.staff
      permission-message: "Only staff (mods/admins) can use this command."
   staffchat:
      description: "Channel where staff can chat together"
      permission: rp.staff
      permission-message: "Only staff (mods/admins) can use this command."
   sc:
      description: "Channel where staff can chat together"
      permission: rp.staff
      permission-message: "Only staff (mods/admins) can use this command."
   rpreload:
      description: "Reloads the Runic Paradise plugin config file."
      usage: /<command>
      permission: runicparadise.rpreload
      permission-message: "You don't have permission: <permission>"
   games:
      description: "Runic Paradise games menu."
      usage: /<command> [option]
   rpgames:
      description: "Runic Paradise games menu."
      usage: /<command> [option]
   events:
      description: "Runic Paradise events tool."
      usage: /<command> [option]
   email:
      usage: /<command>
      permission: rp.admin
   getrunestones:
      usage: /<command>
      permission: rp.admin
   rpversion:
      usage: /<command>